const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "I7 8700K",
      price: 640,
      image: "https://http2.mlstatic.com/D_NQ_NP_910830-MLU43312324305_082020-O.webp",
      category: "Procesador",
      cantidad: 1,
    },
    {
      id: 2,
      title: "EVGA RTX 3060 XC",
      price: 640,
      image: "https://unitytech.uy/wp-content/uploads/2021/06/Evga-RTX-3060-XC-Black-1.jpg",
      category: "VGA",
      cantidad: 1,
    },
    {
      id: 3,
      title: "VTC 600",
      price: 60,
      image: "https://http2.mlstatic.com/D_NQ_NP_641106-MLA46520831345_062021-O.jpg",
      category: "FUENTE",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Vengeance RGB",
      price: 120,
      image: "https://http2.mlstatic.com/D_NQ_NP_991268-MLA48698021738_122021-O.jpg",
      category: "RAM",
      cantidad: 1,
    },
    {
      id: 5,
      title: "StormTrooper",
      price: 180,
      image: "https://c1.neweggimages.com/ProductImage/11-119-245-06.jpg",
      category: "Gabinete",
      cantidad: 1,
    },
    {
      id: 6,
      title: "HDD 1TB",
      price: 90,
      image: "https://pro-gamer.uy/wp-content/uploads/2022/05/wd-blue-pc-desktop-hard-drive-1tb.png",
      category: "HDD",
      cantidad: 1,
    },
    {
      id: 7,
      title: "M2 nvme",
      price: 90,
      image: "https://www.otec.com.uy/imgs/productos/_original_47713.jpg",
      category: "SSD",
      cantidad: 1,
    },
    {
      id: 8,
      title: "ML240R RGB",
      price: 140,
      image: "https://m.media-amazon.com/images/I/41e151XHTFL._AC_.jpg",
      category: "Disipador",
      cantidad: 1,
    },
    {
      id: 9,
      title: "NH-D15",
      price: 200,
      image: "https://m.media-amazon.com/images/I/91Hw1zcAIjL.jpg",
      category: "Disipador",
      cantidad: 1,
    },
    {
      id: 10,
      title: "VX2468",
      price: 150,
      image: "https://www.viewsonic.com/vsAssetFile/es/img/slides/_lcd_display_%28new%29/VX2468-PC-MHD/VX2468_LF03_pc.jpg",
      category: "Monitor",
      cantidad: 1,
    },
  ],
};

export default data;